#!/bin/bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash hpc/submit_free_validation.sh --ell INTEGER [--dry-run]

Environment overrides:
  ROTBOSON_DIR    checkout root (default: $HOME/ROTBOSON_ISCO/ROTBOSON)
  VALIDATION_ROOT generated-data root (default: $ROTBOSON_DIR/validation/results)

ell=1 submits build -> fundamental -> third branch -> exact-frequency array ->
convergence array -> report. ell=0 explicitly dispatches the bundled SPHBOSON
build and free sequence; it is never part of the default ell=1 workflow.
EOF
}

ell=""
dry_run=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --ell)
      [ "$#" -ge 2 ] || { echo "ERROR: --ell requires a value" >&2; exit 2; }
      ell="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ "$ell" =~ ^[0-9]+$ ]] || {
  echo "ERROR: --ell must be a nonnegative integer" >&2
  exit 2
}

ROTBOSON_DIR=${ROTBOSON_DIR:-$HOME/ROTBOSON_ISCO/ROTBOSON}
VALIDATION_ROOT=${VALIDATION_ROOT:-$ROTBOSON_DIR/validation/results}
PYTHON_BIN=${PYTHON_BIN:-python3}
manifest="$ROTBOSON_DIR/validation/benchmarks.json"
validator="$ROTBOSON_DIR/scripts/validate_boson_stars.py"
export ROTBOSON_DIR VALIDATION_ROOT PYTHON_BIN

[ -f "$manifest" ] || { echo "ERROR: missing $manifest" >&2; exit 2; }
mkdir -p "$VALIDATION_ROOT/logs"

echo "Boson-star literature validation"
echo "  checkout: $ROTBOSON_DIR"
echo "  outputs:  $VALIDATION_ROOT"
echo "  resources: partition=h07q2 cpus=4 memory=128G time=72h concurrency=2"
"$PYTHON_BIN" "$validator" --manifest "$manifest" manifest-summary --ell "$ell" --potential free

submit() {
  local dependency="$1"
  shift
  local command=(sbatch --parsable)
  if [ -n "$dependency" ]; then
    command+=("--dependency=afterok:${dependency}")
  fi
  command+=(--export="ALL,ROTBOSON_DIR=$ROTBOSON_DIR,VALIDATION_ROOT=$VALIDATION_ROOT,VALIDATION_ELL=$ell,VALIDATION_POTENTIAL=free,PYTHON_BIN=$PYTHON_BIN")
  command+=("$@")
  if [ "$dry_run" = "1" ]; then
    printf 'DRY-RUN:'
    printf ' %q' "${command[@]}"
    printf '\n'
    DRY_COUNTER=$((DRY_COUNTER + 1))
    SUBMITTED_JOB="DRY${DRY_COUNTER}"
  else
    SUBMITTED_JOB=$("${command[@]}")
    SUBMITTED_JOB=${SUBMITTED_JOB%%;*}
    echo "Submitted job $SUBMITTED_JOB: ${command[*]}" >&2
  fi
}

DRY_COUNTER=0
SUBMITTED_JOB=""
cd "$ROTBOSON_DIR"

if [ "$ell" = "0" ]; then
  submit "" "$ROTBOSON_DIR/hpc/run_validation_build.slurm"
  build_job=$SUBMITTED_JOB
  submit "$build_job" "$ROTBOSON_DIR/hpc/run_validation_l0.slurm"
  sequence_job=$SUBMITTED_JOB
  echo "l=0 route: build=$build_job sequence=$sequence_job"
  echo "No l=0 job is submitted by the default --ell 1 workflow."
  exit 0
fi

"$PYTHON_BIN" "$validator" --manifest "$manifest" profile --ell "$ell" >/dev/null
target_count=$("$PYTHON_BIN" "$validator" --manifest "$manifest" targets --ell "$ell" --potential free | env LD_LIBRARY_PATH= /usr/bin/awk 'END {print NR}')
matrix_count=$("$PYTHON_BIN" "$validator" --manifest "$manifest" matrix --ell "$ell" --potential free --exclude-production | env LD_LIBRARY_PATH= /usr/bin/awk 'END {print NR}')
[ "$target_count" -gt 0 ] && [ "$matrix_count" -gt 0 ] || {
  echo "ERROR: manifest has no l=$ell targets or convergence cases" >&2
  exit 2
}
target_array="0-$((target_count - 1))%2"
matrix_array="0-$((matrix_count - 1))%2"

echo "  exact-frequency array: $target_array ($target_count targets)"
echo "  convergence array:     $matrix_array ($matrix_count non-production grids)"
echo "  production grids are generated by the exact-frequency array and reused."

submit "" "$ROTBOSON_DIR/hpc/run_validation_build.slurm"
build_job=$SUBMITTED_JOB
submit "$build_job" "$ROTBOSON_DIR/hpc/run_validation_fundamental.slurm"
fundamental_job=$SUBMITTED_JOB
submit "$fundamental_job" "$ROTBOSON_DIR/hpc/run_validation_third_branch.slurm"
third_job=$SUBMITTED_JOB
submit "$third_job" --array="$target_array" "$ROTBOSON_DIR/hpc/run_validation_exact.slurm"
exact_job=$SUBMITTED_JOB
submit "$exact_job" --array="$matrix_array" "$ROTBOSON_DIR/hpc/run_validation_convergence.slurm"
convergence_job=$SUBMITTED_JOB
submit "$convergence_job" "$ROTBOSON_DIR/hpc/run_validation_report.slurm"
report_job=$SUBMITTED_JOB

echo "Dependency chain:"
echo "  build=$build_job -> fundamental=$fundamental_job -> third=$third_job"
echo "  -> exact=$exact_job -> convergence=$convergence_job -> report=$report_job"
echo "Reports: $VALIDATION_ROOT/l${ell}/reports/{validation_report.csv,validation_report.json,validation_report.md}"
